{
 "title": "LittleHorse Amplified",
 "tags": [ "littlehorse" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "k8s", "label": "k8s", "query": { "query": "label_values(up,cluster)" } },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kafka_stream_alive_stream_threads{cluster=\"$k8s\"},application_id)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(kafka_stream_alive_stream_threads{cluster=\"$k8s\", application_id=\"$cluster\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Canary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Task Latency",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "canary_task_run_execution_avg", "legendFormat": "latency avg" },
      { "expr": "canary_task_run_execution_max", "legendFormat": "latency max" }
     ]
    },
    {
     "title": "Task Execution Count",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 49 },
     "targets": [
      {
       "expr": "rate(canary_task_run_execution_count[$__rate_interval])",
       "legendFormat": "count"
      }
     ]
    }
   ]
  },
  {
   "title": "Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Metadata Cache Size",
     "type": "stat",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 50 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(cache_name) (lh_cache_size{cache_name=\"metadata\"})",
       "legendFormat": "{{cache_name}}"
      }
     ]
    },
    {
     "title": "Registered Tasks",
     "type": "stat",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 50 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(sum by(task_name) (lh_in_memory_task_queue_size))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Tenants",
     "type": "stat",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 50 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(sum by(tenant_id) (lh_in_memory_task_queue_size))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total SST Files",
     "type": "stat",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(sum by(rocksdb_state_id, task_id) (kafka_stream_state_total_sst_files_size))",
       "legendFormat": "Store: {{rocksdb_state_id}}, Task: {{task_id}}"
      }
     ]
    },
    {
     "title": "Total RocksDB Size",
     "type": "stat",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kafka_stream_state_total_sst_files_size)",
       "legendFormat": "Store: {{rocksdb_state_id}}, Task: {{task_id}}"
      }
     ]
    },
    {
     "title": "In-Memory Task Queue",
     "type": "stat",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 59 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(lh_in_memory_task_queue_size)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Pending Tasks By Tenant",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 59 },
     "targets": [
      {
       "expr": "sum by(tenant_id, task_name) (lh_in_memory_task_queue_size)",
       "legendFormat": "Tenant: {{tenant_id}}, Task: {{task_name}}"
      }
     ]
    },
    {
     "title": "Async waiter size",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 20, "x": 0, "y": 68 },
     "targets": [
      { "expr": "async_waiter_size", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "Standby Tasks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Standby Tasks per Instance",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
     "targets": [
      {
       "expr": "sum by(instance_id, store_name) (standby_partitions)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Standby Tasks Lag per Instance",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
     "targets": [
      {
       "expr": "kafka_streams_lag_standby_store",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Kafka Streams",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Alive Stream Threads",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 81 },
     "targets": [
      {
       "expr": "sum by(topology) (kafka_stream_alive_stream_threads)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Failed Stream Threads",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 81 },
     "targets": [
      {
       "expr": "sum by(topology) (kafka_stream_failed_stream_threads_total{pod=\"$instance\", application_id=\"$cluster\", cluster=\"$k8s\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rebalances",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
     "targets": [
      {
       "expr": "sum by(topology) (increase(kafka_consumer_coordinator_rebalance_total{pod=\"$instance\", application_id=\"$cluster\", cluster=\"$k8s\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rebalance Latency Avg",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(topology) (kafka_consumer_coordinator_rebalance_latency_avg{pod=\"$instance\", application_id=\"$cluster\", cluster=\"$k8s\"}) >= 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total SST Files Size By Task (Stacked)",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by(rocksdb_state_id, task_id) (kafka_stream_state_total_sst_files_size{pod=\"$instance\", application_id=\"$cluster\", cluster=\"$k8s\"})",
       "legendFormat": "Store: {{rocksdb_state_id}}, Task: {{task_id}}"
      }
     ]
    },
    {
     "title": "Task List",
     "type": "table",
     "gridPos": { "h": 12, "w": 8, "x": 8, "y": 98 },
     "targets": [
      {
       "expr": "kafka_stream_state_live_sst_files_size{pod=\"$instance\", application_id=\"$cluster\", cluster=\"$k8s\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Task List Count",
     "type": "table",
     "gridPos": { "h": 12, "w": 8, "x": 16, "y": 98 },
     "targets": [
      {
       "expr": "kafka_stream_state_live_sst_files_size{pod=\"$instance\", application_id=\"$cluster\", cluster=\"$k8s\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Memory Used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1173 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by(id) (jvm_buffer_memory_used_bytes{pod=\"$instance\", cluster=\"$k8s\", application_id=\"$cluster\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Cpu Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1173 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by(instance) (process_cpu_usage{pod=\"$instance\", application_id=\"$cluster\", cluster=\"$k8s\"})",
       "legendFormat": "Server cpu usage"
      },
      {
       "expr": "sum by(instance) (system_cpu_usage{pod=\"$instance\", application_id=\"$cluster\", cluster=\"$k8s\"})",
       "legendFormat": "System cpu usage"
      }
     ]
    },
    {
     "title": "Total SST Files Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1245 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by(pod) (kafka_stream_state_total_sst_files_size{pod=\"$instance\", cluster=\"$k8s\", application_id=\"$cluster\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Free Disk Space",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1245 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(path) (disk_free_bytes{pod=\"$instance\", application_id=\"$cluster\", cluster=\"$k8s\"})",
       "legendFormat": "Available space"
      },
      {
       "expr": "sum by(path) (disk_total_bytes{pod=\"$instance\", application_id=\"$cluster\", cluster=\"$k8s\"}) - sum by(path) (disk_free_bytes{pod=\"$instance\", application_id=\"$cluster\", cluster=\"$k8s\"})",
       "legendFormat": "Usage space"
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Per-Second Message Throughput by Method",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 472 },
     "targets": [
      {
       "expr": "rate(grpc_server_requests_received_messages_total{application_id=\"$cluster\", cluster=\"$k8s\", pod=\"$instance\"}[2m])",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "gRPC Success Rate",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 472 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(statusCode) (grpc_server_processing_duration_seconds_count{pod=\"$instance\", application_id=\"$cluster\", cluster=\"$k8s\"})",
       "legendFormat": "{{method}} {{statusCode}}"
      }
     ]
    },
    {
     "title": "[CLUSTER] Per-Second Message Throughput by Method",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 483 },
     "targets": [
      {
       "expr": "sum by(method) (rate(grpc_server_requests_received_messages_total{application_id=\"$cluster\", cluster=\"$k8s\"}[2m]))",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "gRPC Processing Max",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 483 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by(method) (grpc_server_processing_duration_seconds_max{pod=\"$instance\", application_id=\"$cluster\", cluster=\"$k8s\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "gRPC Processing Avg",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 494 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by(method) (grpc_server_processing_duration_seconds_sum{pod=\"$instance\", application_id=\"$cluster\", cluster=\"$k8s\"}) / sum by(method) (grpc_server_processing_duration_seconds_count{pod=\"$instance\", application_id=\"$cluster\", cluster=\"$k8s\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Producer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kafka Producer Request Size Avg",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1175 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by(topology) (kafka_producer_request_size_avg{pod=\"$instance\", application_id=\"$cluster\", cluster=\"$k8s\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Kafka Producer Request Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1175 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum by(topology) (kafka_producer_request_latency_avg{pod=\"$instance\", application_id=\"$cluster\", cluster=\"$k8s\"})",
       "legendFormat": "Avg {{topology}}"
      }
     ]
    },
    {
     "title": "Kafka Producer Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1191 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(topology) (kafka_producer_record_error_rate{pod=\"$instance\", application_id=\"$cluster\", cluster=\"$k8s\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Kafka Producer Outgoing Byte Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1191 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by(topology) (kafka_producer_outgoing_byte_rate{pod=\"$instance\", cluster=\"$k8s\", application_id=\"$cluster\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Threads Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Thread Commit Latency Avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(topology) (kafka_stream_thread_commit_latency_avg{pod=\"$instance\", application_id=\"$cluster\", cluster=\"$k8s\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thread Commit Latency Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(topology) (kafka_stream_thread_commit_latency_max{pod=\"$instance\", application_id=\"$cluster\", cluster=\"$k8s\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thread Puntuate Latency Avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(topology) (kafka_stream_thread_punctuate_latency_avg{pod=\"$instance\", application_id=\"$cluster\", cluster=\"$k8s\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thread Puntuate Latency Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(topology) (kafka_stream_thread_punctuate_latency_max{pod=\"$instance\", application_id=\"$cluster\", cluster=\"$k8s\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thread Poll Latency Avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(topology) (kafka_stream_thread_poll_latency_avg{pod=\"$instance\", application_id=\"$cluster\", cluster=\"$k8s\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thread Poll Latency Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(topology) (kafka_stream_thread_poll_latency_max{pod=\"$instance\", application_id=\"$cluster\", cluster=\"$k8s\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thread Process Latency Avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(topology) (kafka_stream_thread_process_latency_avg{pod=\"$instance\", application_id=\"$cluster\", cluster=\"$k8s\"} > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thread Process Latency Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(topology) (kafka_stream_thread_process_latency_max{pod=\"$instance\", application_id=\"$cluster\", cluster=\"$k8s\"} > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Per-Second Processing Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum by(topology) (kafka_stream_thread_process_rate{pod=\"$instance\", application_id=\"$cluster\", cluster=\"$k8s\"})",
     "legendFormat": "{{topology}}"
    }
   ]
  },
  {
   "title": "Stream thread blocked time rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(kafka_stream_thread_blocked_time_ns_total[$__rate_interval])",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "Thread Ratio",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Thread Commit Ratio",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 273 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg by(topology) (kafka_stream_thread_commit_ratio{pod=\"$instance\", cluster=\"$k8s\", application_id=\"$cluster\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Thread Punctuate Ratio",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 273 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by(topology) (rate(kafka_stream_thread_punctuate_ratio{pod=\"$instance\", application_id=\"$cluster\", cluster=\"$k8s\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Thread Poll Ratio",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 281 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg by(topology) (kafka_stream_thread_poll_ratio{pod=\"$instance\", application_id=\"$cluster\", cluster=\"$k8s\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Thread Process Ratio",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 281 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg by(topology) (kafka_stream_thread_process_ratio{pod=\"$instance\", application_id=\"$cluster\", cluster=\"$k8s\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Core Topology Ratios",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 289 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg(kafka_stream_thread_commit_ratio{pod=\"$instance\", cluster=\"$k8s\", application_id=\"$cluster\", topology=\"core\"})",
       "legendFormat": "commit_ratio"
      },
      {
       "expr": "avg(kafka_stream_thread_process_ratio{pod=\"$instance\", cluster=\"$k8s\", application_id=\"$cluster\", topology=\"core\"})",
       "legendFormat": "process_ratio"
      },
      {
       "expr": "avg(kafka_stream_thread_poll_ratio{pod=\"$instance\", cluster=\"$k8s\", application_id=\"$cluster\", topology=\"core\"})",
       "legendFormat": "poll_ratio"
      }
     ]
    }
   ]
  },
  {
   "title": "Poll Records",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Poll Records Avg",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 434 },
     "targets": [
      {
       "expr": "sum by(topology) (kafka_stream_thread_poll_records_avg{pod=\"$instance\", cluster=\"$k8s\", application_id=\"$cluster\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Poll Records Max",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 434 },
     "targets": [
      {
       "expr": "sum by(topology) (kafka_stream_thread_poll_records_max{pod=\"$instance\", application_id=\"$cluster\", cluster=\"$k8s\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Debug Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Put Latency in Milliseconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "avg by(topology) (kafka_stream_state_put_latency_avg{pod=\"$instance\", cluster=\"$k8s\", application_id=\"$cluster\"} > 0) / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Get Latency in Milliseconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "avg by(topology) (kafka_stream_state_get_latency_avg{pod=\"$instance\", cluster=\"$k8s\", application_id=\"$cluster\"} > 0) / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KB Written by Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by(topology)(kafka_stream_state_bytes_written_rate{pod=\"$instance\", cluster=\"$k8s\", application_id=\"$cluster\"} >= 0) / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KB Read by Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "avg by(topology)(kafka_stream_state_bytes_read_rate{pod=\"$instance\", cluster=\"$k8s\", application_id=\"$cluster\"} >= 0) / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write stalss by thread id",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum by(thread_id) (kafka_stream_state_write_stall_duration_total{topology=\"core\", rocksdb_state_id=\"core-store\"})",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "Memtable flush rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(avg by(thread_id) (kafka_stream_state_memtable_bytes_flushed_rate{rocksdb_state_id=\"core-store\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memtable flush time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(thread_id) (kafka_stream_state_memtable_flush_time_avg{rocksdb_state_id=\"core-store\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes Written compaction rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(kafka_stream_state_bytes_written_compaction_rate{rocksdb_state_id=\"core-store\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes Read compaction rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 13, "x": 11, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(kafka_stream_state_bytes_read_compaction_rate{rocksdb_state_id=\"core-store\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Num entries in active memtables",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg (kafka_stream_state_num_entries_active_mem_table{rocksdb_state_id=\"core-store\"})",
     "legendFormat": "avg"
    },
    {
     "expr": "max (kafka_stream_state_num_entries_active_mem_table{rocksdb_state_id=\"core-store\"})",
     "legendFormat": "max"
    },
    {
     "expr": "min (kafka_stream_state_num_entries_active_mem_table{rocksdb_state_id=\"core-store\"})",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "Active Memtables size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg (kafka_stream_state_cur_size_active_mem_table{rocksdb_state_id=\"core-store\"})",
     "legendFormat": "avg"
    },
    {
     "expr": "min (kafka_stream_state_cur_size_active_mem_table{rocksdb_state_id=\"core-store\"})",
     "legendFormat": "min"
    },
    {
     "expr": "max (kafka_stream_state_cur_size_active_mem_table{rocksdb_state_id=\"core-store\"})",
     "legendFormat": "max"
    },
    {
     "expr": "sum (kafka_stream_state_cur_size_active_mem_table{rocksdb_state_id=\"core-store\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "All Memtables size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(kafka_stream_state_cur_size_all_mem_tables{rocksdb_state_id=\"core-store\"})",
     "legendFormat": "avg"
    },
    {
     "expr": "min (kafka_stream_state_cur_size_all_mem_tables{rocksdb_state_id=\"core-store\"})",
     "legendFormat": "min"
    },
    {
     "expr": "max (kafka_stream_state_cur_size_all_mem_tables{rocksdb_state_id=\"core-store\"})",
     "legendFormat": "max"
    },
    {
     "expr": "sum (kafka_stream_state_cur_size_all_mem_tables{rocksdb_state_id=\"core-store\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Each entry size avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg (kafka_stream_state_cur_size_active_mem_table{rocksdb_state_id=\"core-store\"}) / avg (kafka_stream_state_num_entries_active_mem_table)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Num Immutable mem tables",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 116 },
   "targets": [
    {
     "expr": "avg(kafka_stream_state_num_immutable_mem_table{rocksdb_state_id=\"core-store\"})",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "State range latency avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "kafka_stream_state_range_latency_avg",
     "legendFormat": "{{task_id}}"
    }
   ]
  }
 ]
}